/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AAggregatePrimaryExpr extends PPrimaryExpr
{
    private PAggregateExpr _aggregateExpr_;

    public AAggregatePrimaryExpr()
    {
    }

    public AAggregatePrimaryExpr(
        PAggregateExpr _aggregateExpr_)
    {
        setAggregateExpr(_aggregateExpr_);

    }
    public Object clone()
    {
        return new AAggregatePrimaryExpr(
            (PAggregateExpr) cloneNode(_aggregateExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAggregatePrimaryExpr(this);
    }

    public PAggregateExpr getAggregateExpr()
    {
        return _aggregateExpr_;
    }

    public void setAggregateExpr(PAggregateExpr node)
    {
        if(_aggregateExpr_ != null)
        {
            _aggregateExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _aggregateExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_aggregateExpr_);
    }

    void removeChild(Node child)
    {
        if(_aggregateExpr_ == child)
        {
            _aggregateExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_aggregateExpr_ == oldChild)
        {
            setAggregateExpr((PAggregateExpr) newChild);
            return;
        }

    }
}
