/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AAndExprTmpOrelseExpr extends PTmpOrelseExpr
{
    private PTmpAndExpr _tmpAndExpr_;

    public AAndExprTmpOrelseExpr()
    {
    }

    public AAndExprTmpOrelseExpr(
        PTmpAndExpr _tmpAndExpr_)
    {
        setTmpAndExpr(_tmpAndExpr_);

    }
    public Object clone()
    {
        return new AAndExprTmpOrelseExpr(
            (PTmpAndExpr) cloneNode(_tmpAndExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExprTmpOrelseExpr(this);
    }

    public PTmpAndExpr getTmpAndExpr()
    {
        return _tmpAndExpr_;
    }

    public void setTmpAndExpr(PTmpAndExpr node)
    {
        if(_tmpAndExpr_ != null)
        {
            _tmpAndExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tmpAndExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tmpAndExpr_);
    }

    void removeChild(Node child)
    {
        if(_tmpAndExpr_ == child)
        {
            _tmpAndExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tmpAndExpr_ == oldChild)
        {
            setTmpAndExpr((PTmpAndExpr) newChild);
            return;
        }

    }
}
