/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AAndthenExpr extends PAndthenExpr
{
    private PAndthenExpr _andthenExpr_;
    private TAndthen _andthen_;
    private PTmpEqualityExpr _tmpEqualityExpr_;

    public AAndthenExpr()
    {
    }

    public AAndthenExpr(
        PAndthenExpr _andthenExpr_,
        TAndthen _andthen_,
        PTmpEqualityExpr _tmpEqualityExpr_)
    {
        setAndthenExpr(_andthenExpr_);

        setAndthen(_andthen_);

        setTmpEqualityExpr(_tmpEqualityExpr_);

    }
    public Object clone()
    {
        return new AAndthenExpr(
            (PAndthenExpr) cloneNode(_andthenExpr_),
            (TAndthen) cloneNode(_andthen_),
            (PTmpEqualityExpr) cloneNode(_tmpEqualityExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndthenExpr(this);
    }

    public PAndthenExpr getAndthenExpr()
    {
        return _andthenExpr_;
    }

    public void setAndthenExpr(PAndthenExpr node)
    {
        if(_andthenExpr_ != null)
        {
            _andthenExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andthenExpr_ = node;
    }

    public TAndthen getAndthen()
    {
        return _andthen_;
    }

    public void setAndthen(TAndthen node)
    {
        if(_andthen_ != null)
        {
            _andthen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andthen_ = node;
    }

    public PTmpEqualityExpr getTmpEqualityExpr()
    {
        return _tmpEqualityExpr_;
    }

    public void setTmpEqualityExpr(PTmpEqualityExpr node)
    {
        if(_tmpEqualityExpr_ != null)
        {
            _tmpEqualityExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tmpEqualityExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_andthenExpr_)
            + toString(_andthen_)
            + toString(_tmpEqualityExpr_);
    }

    void removeChild(Node child)
    {
        if(_andthenExpr_ == child)
        {
            _andthenExpr_ = null;
            return;
        }

        if(_andthen_ == child)
        {
            _andthen_ = null;
            return;
        }

        if(_tmpEqualityExpr_ == child)
        {
            _tmpEqualityExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_andthenExpr_ == oldChild)
        {
            setAndthenExpr((PAndthenExpr) newChild);
            return;
        }

        if(_andthen_ == oldChild)
        {
            setAndthen((TAndthen) newChild);
            return;
        }

        if(_tmpEqualityExpr_ == oldChild)
        {
            setTmpEqualityExpr((PTmpEqualityExpr) newChild);
            return;
        }

    }
}
