/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AAnyCompositePredicate extends PCompositePredicate
{
    private TAny _any_;

    public AAnyCompositePredicate()
    {
    }

    public AAnyCompositePredicate(
        TAny _any_)
    {
        setAny(_any_);

    }
    public Object clone()
    {
        return new AAnyCompositePredicate(
            (TAny) cloneNode(_any_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAnyCompositePredicate(this);
    }

    public TAny getAny()
    {
        return _any_;
    }

    public void setAny(TAny node)
    {
        if(_any_ != null)
        {
            _any_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _any_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_any_);
    }

    void removeChild(Node child)
    {
        if(_any_ == child)
        {
            _any_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_any_ == oldChild)
        {
            setAny((TAny) newChild);
            return;
        }

    }
}
