/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AArrayType extends PType
{
    private TArray _array_;
    private TLt _lt_;
    private PType _type_;
    private TGt _gt_;

    public AArrayType()
    {
    }

    public AArrayType(
        TArray _array_,
        TLt _lt_,
        PType _type_,
        TGt _gt_)
    {
        setArray(_array_);

        setLt(_lt_);

        setType(_type_);

        setGt(_gt_);

    }
    public Object clone()
    {
        return new AArrayType(
            (TArray) cloneNode(_array_),
            (TLt) cloneNode(_lt_),
            (PType) cloneNode(_type_),
            (TGt) cloneNode(_gt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayType(this);
    }

    public TArray getArray()
    {
        return _array_;
    }

    public void setArray(TArray node)
    {
        if(_array_ != null)
        {
            _array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _array_ = node;
    }

    public TLt getLt()
    {
        return _lt_;
    }

    public void setLt(TLt node)
    {
        if(_lt_ != null)
        {
            _lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lt_ = node;
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public TGt getGt()
    {
        return _gt_;
    }

    public void setGt(TGt node)
    {
        if(_gt_ != null)
        {
            _gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_array_)
            + toString(_lt_)
            + toString(_type_)
            + toString(_gt_);
    }

    void removeChild(Node child)
    {
        if(_array_ == child)
        {
            _array_ = null;
            return;
        }

        if(_lt_ == child)
        {
            _lt_ = null;
            return;
        }

        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_gt_ == child)
        {
            _gt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_array_ == oldChild)
        {
            setArray((TArray) newChild);
            return;
        }

        if(_lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

    }
}
