/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ABothRlikeTmpEqualityExpr extends PTmpEqualityExpr
{
    private TIdentifier _left_;
    private TRlike _rlike_;
    private TIdentifier _right_;

    public ABothRlikeTmpEqualityExpr()
    {
    }

    public ABothRlikeTmpEqualityExpr(
        TIdentifier _left_,
        TRlike _rlike_,
        TIdentifier _right_)
    {
        setLeft(_left_);

        setRlike(_rlike_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ABothRlikeTmpEqualityExpr(
            (TIdentifier) cloneNode(_left_),
            (TRlike) cloneNode(_rlike_),
            (TIdentifier) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABothRlikeTmpEqualityExpr(this);
    }

    public TIdentifier getLeft()
    {
        return _left_;
    }

    public void setLeft(TIdentifier node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TRlike getRlike()
    {
        return _rlike_;
    }

    public void setRlike(TRlike node)
    {
        if(_rlike_ != null)
        {
            _rlike_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rlike_ = node;
    }

    public TIdentifier getRight()
    {
        return _right_;
    }

    public void setRight(TIdentifier node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_rlike_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_rlike_ == child)
        {
            _rlike_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((TIdentifier) newChild);
            return;
        }

        if(_rlike_ == oldChild)
        {
            setRlike((TRlike) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((TIdentifier) newChild);
            return;
        }

    }
}
