/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ACollconstrPrimaryExpr extends PPrimaryExpr
{
    private PCollectionConstruction _collectionConstruction_;

    public ACollconstrPrimaryExpr()
    {
    }

    public ACollconstrPrimaryExpr(
        PCollectionConstruction _collectionConstruction_)
    {
        setCollectionConstruction(_collectionConstruction_);

    }
    public Object clone()
    {
        return new ACollconstrPrimaryExpr(
            (PCollectionConstruction) cloneNode(_collectionConstruction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollconstrPrimaryExpr(this);
    }

    public PCollectionConstruction getCollectionConstruction()
    {
        return _collectionConstruction_;
    }

    public void setCollectionConstruction(PCollectionConstruction node)
    {
        if(_collectionConstruction_ != null)
        {
            _collectionConstruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _collectionConstruction_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_collectionConstruction_);
    }

    void removeChild(Node child)
    {
        if(_collectionConstruction_ == child)
        {
            _collectionConstruction_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_collectionConstruction_ == oldChild)
        {
            setCollectionConstruction((PCollectionConstruction) newChild);
            return;
        }

    }
}
