/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ACollectionPrimaryExpr extends PPrimaryExpr
{
    private PCollectionExpr _collectionExpr_;

    public ACollectionPrimaryExpr()
    {
    }

    public ACollectionPrimaryExpr(
        PCollectionExpr _collectionExpr_)
    {
        setCollectionExpr(_collectionExpr_);

    }
    public Object clone()
    {
        return new ACollectionPrimaryExpr(
            (PCollectionExpr) cloneNode(_collectionExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionPrimaryExpr(this);
    }

    public PCollectionExpr getCollectionExpr()
    {
        return _collectionExpr_;
    }

    public void setCollectionExpr(PCollectionExpr node)
    {
        if(_collectionExpr_ != null)
        {
            _collectionExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _collectionExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_collectionExpr_);
    }

    void removeChild(Node child)
    {
        if(_collectionExpr_ == child)
        {
            _collectionExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_collectionExpr_ == oldChild)
        {
            setCollectionExpr((PCollectionExpr) newChild);
            return;
        }

    }
}
