/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AColonIndexAll extends PIndexAll
{
    private PIndex _index_;
    private TColon _colon_;
    private PExprRestricted _exprRestricted_;

    public AColonIndexAll()
    {
    }

    public AColonIndexAll(
        PIndex _index_,
        TColon _colon_,
        PExprRestricted _exprRestricted_)
    {
        setIndex(_index_);

        setColon(_colon_);

        setExprRestricted(_exprRestricted_);

    }
    public Object clone()
    {
        return new AColonIndexAll(
            (PIndex) cloneNode(_index_),
            (TColon) cloneNode(_colon_),
            (PExprRestricted) cloneNode(_exprRestricted_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColonIndexAll(this);
    }

    public PIndex getIndex()
    {
        return _index_;
    }

    public void setIndex(PIndex node)
    {
        if(_index_ != null)
        {
            _index_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _index_ = node;
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public PExprRestricted getExprRestricted()
    {
        return _exprRestricted_;
    }

    public void setExprRestricted(PExprRestricted node)
    {
        if(_exprRestricted_ != null)
        {
            _exprRestricted_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprRestricted_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_index_)
            + toString(_colon_)
            + toString(_exprRestricted_);
    }

    void removeChild(Node child)
    {
        if(_index_ == child)
        {
            _index_ = null;
            return;
        }

        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

        if(_exprRestricted_ == child)
        {
            _exprRestricted_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_index_ == oldChild)
        {
            setIndex((PIndex) newChild);
            return;
        }

        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(_exprRestricted_ == oldChild)
        {
            setExprRestricted((PExprRestricted) newChild);
            return;
        }

    }
}
