/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ADateLiteral extends PLiteral
{
    private PPDate _pDate_;

    public ADateLiteral()
    {
    }

    public ADateLiteral(
        PPDate _pDate_)
    {
        setPDate(_pDate_);

    }
    public Object clone()
    {
        return new ADateLiteral(
            (PPDate) cloneNode(_pDate_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateLiteral(this);
    }

    public PPDate getPDate()
    {
        return _pDate_;
    }

    public void setPDate(PPDate node)
    {
        if(_pDate_ != null)
        {
            _pDate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pDate_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_pDate_);
    }

    void removeChild(Node child)
    {
        if(_pDate_ == child)
        {
            _pDate_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pDate_ == oldChild)
        {
            setPDate((PPDate) newChild);
            return;
        }

    }
}
