/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ADeclarationQueryProgram extends PQueryProgram
{
    private PDeclaration _declaration_;

    public ADeclarationQueryProgram()
    {
    }

    public ADeclarationQueryProgram(
        PDeclaration _declaration_)
    {
        setDeclaration(_declaration_);

    }
    public Object clone()
    {
        return new ADeclarationQueryProgram(
            (PDeclaration) cloneNode(_declaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationQueryProgram(this);
    }

    public PDeclaration getDeclaration()
    {
        return _declaration_;
    }

    public void setDeclaration(PDeclaration node)
    {
        if(_declaration_ != null)
        {
            _declaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _declaration_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_declaration_);
    }

    void removeChild(Node child)
    {
        if(_declaration_ == child)
        {
            _declaration_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_declaration_ == oldChild)
        {
            setDeclaration((PDeclaration) newChild);
            return;
        }

    }
}
