/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AFieldProjection extends PProjection
{
    private PField _field_;

    public AFieldProjection()
    {
    }

    public AFieldProjection(
        PField _field_)
    {
        setField(_field_);

    }
    public Object clone()
    {
        return new AFieldProjection(
            (PField) cloneNode(_field_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFieldProjection(this);
    }

    public PField getField()
    {
        return _field_;
    }

    public void setField(PField node)
    {
        if(_field_ != null)
        {
            _field_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _field_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_field_);
    }

    void removeChild(Node child)
    {
        if(_field_ == child)
        {
            _field_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_field_ == oldChild)
        {
            setField((PField) newChild);
            return;
        }

    }
}
