/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AFirstCommaIndexAll extends PIndexAll
{
    private TIdentifier _identifier_;
    private TComma _comma_;
    private PExprRestricted _exprRestricted_;

    public AFirstCommaIndexAll()
    {
    }

    public AFirstCommaIndexAll(
        TIdentifier _identifier_,
        TComma _comma_,
        PExprRestricted _exprRestricted_)
    {
        setIdentifier(_identifier_);

        setComma(_comma_);

        setExprRestricted(_exprRestricted_);

    }
    public Object clone()
    {
        return new AFirstCommaIndexAll(
            (TIdentifier) cloneNode(_identifier_),
            (TComma) cloneNode(_comma_),
            (PExprRestricted) cloneNode(_exprRestricted_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFirstCommaIndexAll(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PExprRestricted getExprRestricted()
    {
        return _exprRestricted_;
    }

    public void setExprRestricted(PExprRestricted node)
    {
        if(_exprRestricted_ != null)
        {
            _exprRestricted_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprRestricted_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_comma_)
            + toString(_exprRestricted_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_exprRestricted_ == child)
        {
            _exprRestricted_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_exprRestricted_ == oldChild)
        {
            setExprRestricted((PExprRestricted) newChild);
            return;
        }

    }
}
