/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AIdentifierFieldPostfixExpr extends PPostfixExpr
{
    private TIdentifier _left_;
    private PDotarrow _dotarrow_;
    private TIdentifier _right_;

    public AIdentifierFieldPostfixExpr()
    {
    }

    public AIdentifierFieldPostfixExpr(
        TIdentifier _left_,
        PDotarrow _dotarrow_,
        TIdentifier _right_)
    {
        setLeft(_left_);

        setDotarrow(_dotarrow_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AIdentifierFieldPostfixExpr(
            (TIdentifier) cloneNode(_left_),
            (PDotarrow) cloneNode(_dotarrow_),
            (TIdentifier) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentifierFieldPostfixExpr(this);
    }

    public TIdentifier getLeft()
    {
        return _left_;
    }

    public void setLeft(TIdentifier node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public PDotarrow getDotarrow()
    {
        return _dotarrow_;
    }

    public void setDotarrow(PDotarrow node)
    {
        if(_dotarrow_ != null)
        {
            _dotarrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dotarrow_ = node;
    }

    public TIdentifier getRight()
    {
        return _right_;
    }

    public void setRight(TIdentifier node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_dotarrow_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_dotarrow_ == child)
        {
            _dotarrow_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((TIdentifier) newChild);
            return;
        }

        if(_dotarrow_ == oldChild)
        {
            setDotarrow((PDotarrow) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((TIdentifier) newChild);
            return;
        }

    }
}
