/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AIncludeDeclaration extends PDeclaration
{
    private PIncludeClause _includeClause_;

    public AIncludeDeclaration()
    {
    }

    public AIncludeDeclaration(
        PIncludeClause _includeClause_)
    {
        setIncludeClause(_includeClause_);

    }
    public Object clone()
    {
        return new AIncludeDeclaration(
            (PIncludeClause) cloneNode(_includeClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIncludeDeclaration(this);
    }

    public PIncludeClause getIncludeClause()
    {
        return _includeClause_;
    }

    public void setIncludeClause(PIncludeClause node)
    {
        if(_includeClause_ != null)
        {
            _includeClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _includeClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_includeClause_);
    }

    void removeChild(Node child)
    {
        if(_includeClause_ == child)
        {
            _includeClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_includeClause_ == oldChild)
        {
            setIncludeClause((PIncludeClause) newChild);
            return;
        }

    }
}
