/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ALastAndthenExpr extends PAndthenExpr
{
    private PAndthenExpr _andthenExpr_;
    private TAndthen _andthen_;
    private TIdentifier _identifier_;

    public ALastAndthenExpr()
    {
    }

    public ALastAndthenExpr(
        PAndthenExpr _andthenExpr_,
        TAndthen _andthen_,
        TIdentifier _identifier_)
    {
        setAndthenExpr(_andthenExpr_);

        setAndthen(_andthen_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new ALastAndthenExpr(
            (PAndthenExpr) cloneNode(_andthenExpr_),
            (TAndthen) cloneNode(_andthen_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALastAndthenExpr(this);
    }

    public PAndthenExpr getAndthenExpr()
    {
        return _andthenExpr_;
    }

    public void setAndthenExpr(PAndthenExpr node)
    {
        if(_andthenExpr_ != null)
        {
            _andthenExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andthenExpr_ = node;
    }

    public TAndthen getAndthen()
    {
        return _andthen_;
    }

    public void setAndthen(TAndthen node)
    {
        if(_andthen_ != null)
        {
            _andthen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andthen_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_andthenExpr_)
            + toString(_andthen_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_andthenExpr_ == child)
        {
            _andthenExpr_ = null;
            return;
        }

        if(_andthen_ == child)
        {
            _andthen_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_andthenExpr_ == oldChild)
        {
            setAndthenExpr((PAndthenExpr) newChild);
            return;
        }

        if(_andthen_ == oldChild)
        {
            setAndthen((TAndthen) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
