/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ALastUnionAdditiveExpr extends PAdditiveExpr
{
    private PAdditiveExpr _additiveExpr_;
    private TUnion _union_;
    private TIdentifier _identifier_;

    public ALastUnionAdditiveExpr()
    {
    }

    public ALastUnionAdditiveExpr(
        PAdditiveExpr _additiveExpr_,
        TUnion _union_,
        TIdentifier _identifier_)
    {
        setAdditiveExpr(_additiveExpr_);

        setUnion(_union_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new ALastUnionAdditiveExpr(
            (PAdditiveExpr) cloneNode(_additiveExpr_),
            (TUnion) cloneNode(_union_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALastUnionAdditiveExpr(this);
    }

    public PAdditiveExpr getAdditiveExpr()
    {
        return _additiveExpr_;
    }

    public void setAdditiveExpr(PAdditiveExpr node)
    {
        if(_additiveExpr_ != null)
        {
            _additiveExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additiveExpr_ = node;
    }

    public TUnion getUnion()
    {
        return _union_;
    }

    public void setUnion(TUnion node)
    {
        if(_union_ != null)
        {
            _union_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _union_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additiveExpr_)
            + toString(_union_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_additiveExpr_ == child)
        {
            _additiveExpr_ = null;
            return;
        }

        if(_union_ == child)
        {
            _union_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additiveExpr_ == oldChild)
        {
            setAdditiveExpr((PAdditiveExpr) newChild);
            return;
        }

        if(_union_ == oldChild)
        {
            setUnion((TUnion) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
