/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ALiteralPrimaryExpr extends PPrimaryExpr
{
    private PLiteral _literal_;

    public ALiteralPrimaryExpr()
    {
    }

    public ALiteralPrimaryExpr(
        PLiteral _literal_)
    {
        setLiteral(_literal_);

    }
    public Object clone()
    {
        return new ALiteralPrimaryExpr(
            (PLiteral) cloneNode(_literal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALiteralPrimaryExpr(this);
    }

    public PLiteral getLiteral()
    {
        return _literal_;
    }

    public void setLiteral(PLiteral node)
    {
        if(_literal_ != null)
        {
            _literal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _literal_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_literal_);
    }

    void removeChild(Node child)
    {
        if(_literal_ == child)
        {
            _literal_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_literal_ == oldChild)
        {
            setLiteral((PLiteral) newChild);
            return;
        }

    }
}
