/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AMethodPostfixExpr extends PPostfixExpr
{
    private PPostfixExpr _postfixExpr_;
    private PDotarrow _dotarrow_;
    private TIdentifier _identifier_;
    private TBracketL _bracketL_;
    private PValueList _valueList_;
    private TBracketR _bracketR_;

    public AMethodPostfixExpr()
    {
    }

    public AMethodPostfixExpr(
        PPostfixExpr _postfixExpr_,
        PDotarrow _dotarrow_,
        TIdentifier _identifier_,
        TBracketL _bracketL_,
        PValueList _valueList_,
        TBracketR _bracketR_)
    {
        setPostfixExpr(_postfixExpr_);

        setDotarrow(_dotarrow_);

        setIdentifier(_identifier_);

        setBracketL(_bracketL_);

        setValueList(_valueList_);

        setBracketR(_bracketR_);

    }
    public Object clone()
    {
        return new AMethodPostfixExpr(
            (PPostfixExpr) cloneNode(_postfixExpr_),
            (PDotarrow) cloneNode(_dotarrow_),
            (TIdentifier) cloneNode(_identifier_),
            (TBracketL) cloneNode(_bracketL_),
            (PValueList) cloneNode(_valueList_),
            (TBracketR) cloneNode(_bracketR_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodPostfixExpr(this);
    }

    public PPostfixExpr getPostfixExpr()
    {
        return _postfixExpr_;
    }

    public void setPostfixExpr(PPostfixExpr node)
    {
        if(_postfixExpr_ != null)
        {
            _postfixExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _postfixExpr_ = node;
    }

    public PDotarrow getDotarrow()
    {
        return _dotarrow_;
    }

    public void setDotarrow(PDotarrow node)
    {
        if(_dotarrow_ != null)
        {
            _dotarrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dotarrow_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TBracketL getBracketL()
    {
        return _bracketL_;
    }

    public void setBracketL(TBracketL node)
    {
        if(_bracketL_ != null)
        {
            _bracketL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bracketL_ = node;
    }

    public PValueList getValueList()
    {
        return _valueList_;
    }

    public void setValueList(PValueList node)
    {
        if(_valueList_ != null)
        {
            _valueList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _valueList_ = node;
    }

    public TBracketR getBracketR()
    {
        return _bracketR_;
    }

    public void setBracketR(TBracketR node)
    {
        if(_bracketR_ != null)
        {
            _bracketR_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bracketR_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_postfixExpr_)
            + toString(_dotarrow_)
            + toString(_identifier_)
            + toString(_bracketL_)
            + toString(_valueList_)
            + toString(_bracketR_);
    }

    void removeChild(Node child)
    {
        if(_postfixExpr_ == child)
        {
            _postfixExpr_ = null;
            return;
        }

        if(_dotarrow_ == child)
        {
            _dotarrow_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_bracketL_ == child)
        {
            _bracketL_ = null;
            return;
        }

        if(_valueList_ == child)
        {
            _valueList_ = null;
            return;
        }

        if(_bracketR_ == child)
        {
            _bracketR_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_postfixExpr_ == oldChild)
        {
            setPostfixExpr((PPostfixExpr) newChild);
            return;
        }

        if(_dotarrow_ == oldChild)
        {
            setDotarrow((PDotarrow) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_bracketL_ == oldChild)
        {
            setBracketL((TBracketL) newChild);
            return;
        }

        if(_valueList_ == oldChild)
        {
            setValueList((PValueList) newChild);
            return;
        }

        if(_bracketR_ == oldChild)
        {
            setBracketR((TBracketR) newChild);
            return;
        }

    }
}
