/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AOrelseTmpOrExpr extends PTmpOrExpr
{
    private PTmpOrelseExpr _tmpOrelseExpr_;

    public AOrelseTmpOrExpr()
    {
    }

    public AOrelseTmpOrExpr(
        PTmpOrelseExpr _tmpOrelseExpr_)
    {
        setTmpOrelseExpr(_tmpOrelseExpr_);

    }
    public Object clone()
    {
        return new AOrelseTmpOrExpr(
            (PTmpOrelseExpr) cloneNode(_tmpOrelseExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrelseTmpOrExpr(this);
    }

    public PTmpOrelseExpr getTmpOrelseExpr()
    {
        return _tmpOrelseExpr_;
    }

    public void setTmpOrelseExpr(PTmpOrelseExpr node)
    {
        if(_tmpOrelseExpr_ != null)
        {
            _tmpOrelseExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tmpOrelseExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tmpOrelseExpr_);
    }

    void removeChild(Node child)
    {
        if(_tmpOrelseExpr_ == child)
        {
            _tmpOrelseExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tmpOrelseExpr_ == oldChild)
        {
            setTmpOrelseExpr((PTmpOrelseExpr) newChild);
            return;
        }

    }
}
