/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class APDate extends PPDate
{
    private TDate _date_;
    private TQuote _q1_;
    private PDateContent _dateContent_;
    private TQuote _q2_;

    public APDate()
    {
    }

    public APDate(
        TDate _date_,
        TQuote _q1_,
        PDateContent _dateContent_,
        TQuote _q2_)
    {
        setDate(_date_);

        setQ1(_q1_);

        setDateContent(_dateContent_);

        setQ2(_q2_);

    }
    public Object clone()
    {
        return new APDate(
            (TDate) cloneNode(_date_),
            (TQuote) cloneNode(_q1_),
            (PDateContent) cloneNode(_dateContent_),
            (TQuote) cloneNode(_q2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPDate(this);
    }

    public TDate getDate()
    {
        return _date_;
    }

    public void setDate(TDate node)
    {
        if(_date_ != null)
        {
            _date_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _date_ = node;
    }

    public TQuote getQ1()
    {
        return _q1_;
    }

    public void setQ1(TQuote node)
    {
        if(_q1_ != null)
        {
            _q1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _q1_ = node;
    }

    public PDateContent getDateContent()
    {
        return _dateContent_;
    }

    public void setDateContent(PDateContent node)
    {
        if(_dateContent_ != null)
        {
            _dateContent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dateContent_ = node;
    }

    public TQuote getQ2()
    {
        return _q2_;
    }

    public void setQ2(TQuote node)
    {
        if(_q2_ != null)
        {
            _q2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _q2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_date_)
            + toString(_q1_)
            + toString(_dateContent_)
            + toString(_q2_);
    }

    void removeChild(Node child)
    {
        if(_date_ == child)
        {
            _date_ = null;
            return;
        }

        if(_q1_ == child)
        {
            _q1_ = null;
            return;
        }

        if(_dateContent_ == child)
        {
            _dateContent_ = null;
            return;
        }

        if(_q2_ == child)
        {
            _q2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_date_ == oldChild)
        {
            setDate((TDate) newChild);
            return;
        }

        if(_q1_ == oldChild)
        {
            setQ1((TQuote) newChild);
            return;
        }

        if(_dateContent_ == oldChild)
        {
            setDateContent((PDateContent) newChild);
            return;
        }

        if(_q2_ == oldChild)
        {
            setQ2((TQuote) newChild);
            return;
        }

    }
}
