/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class APlusAdditiveExpr extends PAdditiveExpr
{
    private PAdditiveExpr _additiveExpr_;
    private TPlus _plus_;
    private PMultiplicativeExpr _multiplicativeExpr_;

    public APlusAdditiveExpr()
    {
    }

    public APlusAdditiveExpr(
        PAdditiveExpr _additiveExpr_,
        TPlus _plus_,
        PMultiplicativeExpr _multiplicativeExpr_)
    {
        setAdditiveExpr(_additiveExpr_);

        setPlus(_plus_);

        setMultiplicativeExpr(_multiplicativeExpr_);

    }
    public Object clone()
    {
        return new APlusAdditiveExpr(
            (PAdditiveExpr) cloneNode(_additiveExpr_),
            (TPlus) cloneNode(_plus_),
            (PMultiplicativeExpr) cloneNode(_multiplicativeExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAdditiveExpr(this);
    }

    public PAdditiveExpr getAdditiveExpr()
    {
        return _additiveExpr_;
    }

    public void setAdditiveExpr(PAdditiveExpr node)
    {
        if(_additiveExpr_ != null)
        {
            _additiveExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additiveExpr_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PMultiplicativeExpr getMultiplicativeExpr()
    {
        return _multiplicativeExpr_;
    }

    public void setMultiplicativeExpr(PMultiplicativeExpr node)
    {
        if(_multiplicativeExpr_ != null)
        {
            _multiplicativeExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplicativeExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additiveExpr_)
            + toString(_plus_)
            + toString(_multiplicativeExpr_);
    }

    void removeChild(Node child)
    {
        if(_additiveExpr_ == child)
        {
            _additiveExpr_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_multiplicativeExpr_ == child)
        {
            _multiplicativeExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additiveExpr_ == oldChild)
        {
            setAdditiveExpr((PAdditiveExpr) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_multiplicativeExpr_ == oldChild)
        {
            setMultiplicativeExpr((PMultiplicativeExpr) newChild);
            return;
        }

    }
}
