/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AQuantifierExprTmpAndExpr extends PTmpAndExpr
{
    private PQuantifierExpr _quantifierExpr_;

    public AQuantifierExprTmpAndExpr()
    {
    }

    public AQuantifierExprTmpAndExpr(
        PQuantifierExpr _quantifierExpr_)
    {
        setQuantifierExpr(_quantifierExpr_);

    }
    public Object clone()
    {
        return new AQuantifierExprTmpAndExpr(
            (PQuantifierExpr) cloneNode(_quantifierExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQuantifierExprTmpAndExpr(this);
    }

    public PQuantifierExpr getQuantifierExpr()
    {
        return _quantifierExpr_;
    }

    public void setQuantifierExpr(PQuantifierExpr node)
    {
        if(_quantifierExpr_ != null)
        {
            _quantifierExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _quantifierExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_quantifierExpr_);
    }

    void removeChild(Node child)
    {
        if(_quantifierExpr_ == child)
        {
            _quantifierExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_quantifierExpr_ == oldChild)
        {
            setQuantifierExpr((PQuantifierExpr) newChild);
            return;
        }

    }
}
