/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ARelationalExpr extends PExpr
{
    private PExpr _left_;
    private PCompareToken _compareToken_;
    private PCompositePredicate _compositePredicate_;
    private PExpr _right_;

    public ARelationalExpr()
    {
    }

    public ARelationalExpr(
        PExpr _left_,
        PCompareToken _compareToken_,
        PCompositePredicate _compositePredicate_,
        PExpr _right_)
    {
        setLeft(_left_);

        setCompareToken(_compareToken_);

        setCompositePredicate(_compositePredicate_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ARelationalExpr(
            (PExpr) cloneNode(_left_),
            (PCompareToken) cloneNode(_compareToken_),
            (PCompositePredicate) cloneNode(_compositePredicate_),
            (PExpr) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationalExpr(this);
    }

    public PExpr getLeft()
    {
        return _left_;
    }

    public void setLeft(PExpr node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public PCompareToken getCompareToken()
    {
        return _compareToken_;
    }

    public void setCompareToken(PCompareToken node)
    {
        if(_compareToken_ != null)
        {
            _compareToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compareToken_ = node;
    }

    public PCompositePredicate getCompositePredicate()
    {
        return _compositePredicate_;
    }

    public void setCompositePredicate(PCompositePredicate node)
    {
        if(_compositePredicate_ != null)
        {
            _compositePredicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compositePredicate_ = node;
    }

    public PExpr getRight()
    {
        return _right_;
    }

    public void setRight(PExpr node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_compareToken_)
            + toString(_compositePredicate_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_compareToken_ == child)
        {
            _compareToken_ = null;
            return;
        }

        if(_compositePredicate_ == child)
        {
            _compositePredicate_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PExpr) newChild);
            return;
        }

        if(_compareToken_ == oldChild)
        {
            setCompareToken((PCompareToken) newChild);
            return;
        }

        if(_compositePredicate_ == oldChild)
        {
            setCompositePredicate((PCompositePredicate) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PExpr) newChild);
            return;
        }

    }
}
