/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ATimeLiteral extends PLiteral
{
    private PPTime _pTime_;

    public ATimeLiteral()
    {
    }

    public ATimeLiteral(
        PPTime _pTime_)
    {
        setPTime(_pTime_);

    }
    public Object clone()
    {
        return new ATimeLiteral(
            (PPTime) cloneNode(_pTime_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeLiteral(this);
    }

    public PPTime getPTime()
    {
        return _pTime_;
    }

    public void setPTime(PPTime node)
    {
        if(_pTime_ != null)
        {
            _pTime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTime_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_pTime_);
    }

    void removeChild(Node child)
    {
        if(_pTime_ == child)
        {
            _pTime_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pTime_ == oldChild)
        {
            setPTime((PPTime) newChild);
            return;
        }

    }
}
