/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ATmpOrExpr extends PTmpOrExpr
{
    private PTmpOrExpr _tmpOrExpr_;
    private TOr _or_;
    private PTmpOrelseExpr _tmpOrelseExpr_;

    public ATmpOrExpr()
    {
    }

    public ATmpOrExpr(
        PTmpOrExpr _tmpOrExpr_,
        TOr _or_,
        PTmpOrelseExpr _tmpOrelseExpr_)
    {
        setTmpOrExpr(_tmpOrExpr_);

        setOr(_or_);

        setTmpOrelseExpr(_tmpOrelseExpr_);

    }
    public Object clone()
    {
        return new ATmpOrExpr(
            (PTmpOrExpr) cloneNode(_tmpOrExpr_),
            (TOr) cloneNode(_or_),
            (PTmpOrelseExpr) cloneNode(_tmpOrelseExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmpOrExpr(this);
    }

    public PTmpOrExpr getTmpOrExpr()
    {
        return _tmpOrExpr_;
    }

    public void setTmpOrExpr(PTmpOrExpr node)
    {
        if(_tmpOrExpr_ != null)
        {
            _tmpOrExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tmpOrExpr_ = node;
    }

    public TOr getOr()
    {
        return _or_;
    }

    public void setOr(TOr node)
    {
        if(_or_ != null)
        {
            _or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _or_ = node;
    }

    public PTmpOrelseExpr getTmpOrelseExpr()
    {
        return _tmpOrelseExpr_;
    }

    public void setTmpOrelseExpr(PTmpOrelseExpr node)
    {
        if(_tmpOrelseExpr_ != null)
        {
            _tmpOrelseExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tmpOrelseExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tmpOrExpr_)
            + toString(_or_)
            + toString(_tmpOrelseExpr_);
    }

    void removeChild(Node child)
    {
        if(_tmpOrExpr_ == child)
        {
            _tmpOrExpr_ = null;
            return;
        }

        if(_or_ == child)
        {
            _or_ = null;
            return;
        }

        if(_tmpOrelseExpr_ == child)
        {
            _tmpOrelseExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tmpOrExpr_ == oldChild)
        {
            setTmpOrExpr((PTmpOrExpr) newChild);
            return;
        }

        if(_or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(_tmpOrelseExpr_ == oldChild)
        {
            setTmpOrelseExpr((PTmpOrelseExpr) newChild);
            return;
        }

    }
}
