/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ATmpExprProjection extends PProjection
{
    private PExprRestricted _exprRestricted_;
    private PAsIdentifier _asIdentifier_;

    public ATmpExprProjection()
    {
    }

    public ATmpExprProjection(
        PExprRestricted _exprRestricted_,
        PAsIdentifier _asIdentifier_)
    {
        setExprRestricted(_exprRestricted_);

        setAsIdentifier(_asIdentifier_);

    }
    public Object clone()
    {
        return new ATmpExprProjection(
            (PExprRestricted) cloneNode(_exprRestricted_),
            (PAsIdentifier) cloneNode(_asIdentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmpExprProjection(this);
    }

    public PExprRestricted getExprRestricted()
    {
        return _exprRestricted_;
    }

    public void setExprRestricted(PExprRestricted node)
    {
        if(_exprRestricted_ != null)
        {
            _exprRestricted_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprRestricted_ = node;
    }

    public PAsIdentifier getAsIdentifier()
    {
        return _asIdentifier_;
    }

    public void setAsIdentifier(PAsIdentifier node)
    {
        if(_asIdentifier_ != null)
        {
            _asIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _asIdentifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprRestricted_)
            + toString(_asIdentifier_);
    }

    void removeChild(Node child)
    {
        if(_exprRestricted_ == child)
        {
            _exprRestricted_ = null;
            return;
        }

        if(_asIdentifier_ == child)
        {
            _asIdentifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprRestricted_ == oldChild)
        {
            setExprRestricted((PExprRestricted) newChild);
            return;
        }

        if(_asIdentifier_ == oldChild)
        {
            setAsIdentifier((PAsIdentifier) newChild);
            return;
        }

    }
}
