/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class ATupleListReturnQuery extends PReturnQuery
{
    private PTupleList _tupleList_;

    public ATupleListReturnQuery()
    {
    }

    public ATupleListReturnQuery(
        PTupleList _tupleList_)
    {
        setTupleList(_tupleList_);

    }
    public Object clone()
    {
        return new ATupleListReturnQuery(
            (PTupleList) cloneNode(_tupleList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATupleListReturnQuery(this);
    }

    public PTupleList getTupleList()
    {
        return _tupleList_;
    }

    public void setTupleList(PTupleList node)
    {
        if(_tupleList_ != null)
        {
            _tupleList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tupleList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tupleList_);
    }

    void removeChild(Node child)
    {
        if(_tupleList_ == child)
        {
            _tupleList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tupleList_ == oldChild)
        {
            setTupleList((PTupleList) newChild);
            return;
        }

    }
}
