/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import java.util.*;
import org.acre.lang.analysis.*;

public final class AUndefinedPrimaryExpr extends PPrimaryExpr
{
    private PUndefinedExpr _undefinedExpr_;

    public AUndefinedPrimaryExpr()
    {
    }

    public AUndefinedPrimaryExpr(
        PUndefinedExpr _undefinedExpr_)
    {
        setUndefinedExpr(_undefinedExpr_);

    }
    public Object clone()
    {
        return new AUndefinedPrimaryExpr(
            (PUndefinedExpr) cloneNode(_undefinedExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUndefinedPrimaryExpr(this);
    }

    public PUndefinedExpr getUndefinedExpr()
    {
        return _undefinedExpr_;
    }

    public void setUndefinedExpr(PUndefinedExpr node)
    {
        if(_undefinedExpr_ != null)
        {
            _undefinedExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _undefinedExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_undefinedExpr_);
    }

    void removeChild(Node child)
    {
        if(_undefinedExpr_ == child)
        {
            _undefinedExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_undefinedExpr_ == oldChild)
        {
            setUndefinedExpr((PUndefinedExpr) newChild);
            return;
        }

    }
}
