/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import org.acre.lang.analysis.*;

public final class TBinor extends Token
{
    public TBinor()
    {
        super.setText("||");
    }

    public TBinor(int line, int pos)
    {
        super.setText("||");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBinor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBinor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBinor text.");
    }
}
