/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import org.acre.lang.analysis.*;

public final class TSetAnd extends Token
{
    public TSetAnd()
    {
        super.setText("^");
    }

    public TSetAnd(int line, int pos)
    {
        super.setText("^");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSetAnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSetAnd(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSetAnd text.");
    }
}
