/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.acre.lang.node;

import org.acre.lang.analysis.*;

public final class X1PExpr extends XPExpr
{
    private XPExpr _xPExpr_;
    private PExpr _pExpr_;

    public X1PExpr()
    {
    }

    public X1PExpr(
        XPExpr _xPExpr_,
        PExpr _pExpr_)
    {
        setXPExpr(_xPExpr_);
        setPExpr(_pExpr_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPExpr getXPExpr()
    {
        return _xPExpr_;
    }

    public void setXPExpr(XPExpr node)
    {
        if(_xPExpr_ != null)
        {
            _xPExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPExpr_ = node;
    }

    public PExpr getPExpr()
    {
        return _pExpr_;
    }

    public void setPExpr(PExpr node)
    {
        if(_pExpr_ != null)
        {
            _pExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pExpr_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPExpr_ == child)
        {
            _xPExpr_ = null;
        }

        if(_pExpr_ == child)
        {
            _pExpr_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPExpr_) +
            toString(_pExpr_);
    }
}
